#!/usr/bin/env python3
"""
Load VT-Tiny-MOT samples as multi-object, multi-modal trajectories.

This is the shape used by the loader:

  one sequence data point =
    one full sequence
      frames: [t0, t1, ..., tN]
      objects:
        track_id A:
          rgb trajectory over the sequence
          thermal trajectory over the sequence
        track_id B:
          rgb trajectory over the sequence
          thermal trajectory over the sequence
        ...

  one window data point =
    same structure, but clipped to a fixed-length time window

The input CSV is generated by extract_vt_tiny_mot_trajectories.py:
  outputs/vt_tiny_mot_trajectories/observations_train.csv
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np


DEFAULT_CSV = (
    Path("outputs")
    / "vt_tiny_mot_trajectories"
    / "observations_train.csv"
)


FEATURE_NAMES = ("cx", "cy", "x", "y", "w", "h", "vx", "vy", "speed")
MODALITIES = ("rgb", "thermal")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Load multi-object, multi-modal trajectory samples."
    )
    parser.add_argument("--csv-path", type=Path, default=DEFAULT_CSV)
    parser.add_argument(
        "--sample-mode",
        choices=("sequence", "window"),
        default="sequence",
        help="sequence uses each full video sequence as one data point; window uses fixed-length clips.",
    )
    parser.add_argument("--window-size", type=int, default=8)
    parser.add_argument("--stride", type=int, default=1)
    parser.add_argument(
        "--min-visible-frames",
        type=int,
        default=2,
        help="Keep objects visible in at least this many frames in either modality.",
    )
    parser.add_argument(
        "--require-both-modalities",
        action="store_true",
        help="Keep only objects that appear in both RGB and thermal within the sample.",
    )
    parser.add_argument("--sequence", default=None)
    parser.add_argument("--limit", type=int, default=2)
    return parser.parse_args()


def to_float(value: str) -> float | None:
    if value == "" or value is None:
        return None
    return float(value)


def to_int(value: str) -> int | None:
    if value == "" or value is None:
        return None
    return int(float(value))


def read_observations(csv_path: Path) -> dict[str, dict[int, dict[str, dict[str, Any]]]]:
    """
    Return nested observations:
      sequence -> frame_id -> track_id -> row dict
    """
    sequences: dict[str, dict[int, dict[str, dict[str, Any]]]] = defaultdict(
        lambda: defaultdict(dict)
    )

    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            sequence = row["sequence"]
            frame_id = to_int(row["frame_id"])
            track_id = row["track_id"]
            if frame_id is None:
                continue
            sequences[sequence][frame_id][track_id] = row

    return {seq: dict(frames) for seq, frames in sequences.items()}


def has_modality(row: dict[str, str], modality: str) -> bool:
    return row.get(f"{modality}_cx", "") != "" and row.get(f"{modality}_cy", "") != ""


def extract_feature(row: dict[str, str] | None, modality: str) -> tuple[np.ndarray, bool]:
    """
    Feature vector:
      [cx, cy, x, y, w, h, vx_px_per_frame, vy_px_per_frame, speed_px_per_frame]
    """
    feature = np.zeros((len(FEATURE_NAMES),), dtype=np.float32)
    if row is None or not has_modality(row, modality):
        return feature, False

    values = [
        to_float(row[f"{modality}_cx"]),
        to_float(row[f"{modality}_cy"]),
        to_float(row[f"{modality}_x"]),
        to_float(row[f"{modality}_y"]),
        to_float(row[f"{modality}_w"]),
        to_float(row[f"{modality}_h"]),
        to_float(row[f"{modality}_vx_px_per_frame"]),
        to_float(row[f"{modality}_vy_px_per_frame"]),
        to_float(row[f"{modality}_speed_px_per_frame"]),
    ]

    for idx, value in enumerate(values):
        feature[idx] = 0.0 if value is None else float(value)

    return feature, True


class VTTinyMOTTrajectoryDataset:
    """
    Plain Python dataset for multi-object, multi-modal trajectory samples.

    A single data point is one trajectory sample. By default, sample_mode="sequence",
    so one data point is one complete video sequence. If sample_mode="window", one
    data point is one fixed-length clip from a sequence.

    __getitem__ returns:
      {
        "sequence": str,
        "frames": int64 array, shape [T],
        "track_ids": list[str], length O,
        "category_ids": int64 array, shape [O],
        "category_names": list[str], length O,
        "features": float32 array, shape [O, T, 2, F],
        "mask": bool array, shape [O, T, 2],
        "modalities": ["rgb", "thermal"],
        "feature_names": ["cx", "cy", "x", "y", "w", "h", "vx", "vy", "speed"],
        "sample_mode": "sequence" or "window",
      }

    Key/value meanings for one data point:
      sequence:
        The video sequence name, for example "DJI_0022_1".

      frames:
        Sorted frame ids included in this sample. In sequence mode this is the
        full frame list for the sequence, for example [0, 1, ..., 129]. In
        window mode this is the selected fixed-length frame window.

      track_ids:
        Object identities included in this sample. track_ids[i] identifies the
        i-th object stored in features[i], mask[i], category_ids[i], and
        category_names[i].

      category_ids:
        Category id for each object, aligned with track_ids. Shape [O].

      category_names:
        Category name for each object, aligned with track_ids. Examples include
        "ship", "car", "pedestrian", and "drone".

      features:
        Numeric trajectory tensor with shape [O, T, 2, F].
          O: number of objects in the sample.
          T: number of sorted frames in this sample.
          2: modality index, where modalities[0] is "rgb" and modalities[1]
             is "thermal".
          F: feature index, where feature_names gives the meaning of each
             value.

        features[i, t, m] is the m-th modality trajectory feature vector for
        object track_ids[i] at frame frames[t].

      mask:
        Boolean visibility mask with shape [O, T, 2].
        mask[i, t, m] is True when object track_ids[i] has a valid annotation
        in modality modalities[m] at frame frames[t]. When mask is False, the
        matching features vector is zero-filled and should usually be ignored
        by loss functions or temporal aggregation.

      objects:
        A metadata list for the retained objects. Each item contains:
          track_id: the object identity.
          category_id: object category id.
          category_name: object category name.
          visible_rgb_frames: number of frames where RGB annotation exists.
          visible_thermal_frames: number of frames where thermal annotation exists.

      modalities:
        The modality order used by the third dimension of features and mask:
        ["rgb", "thermal"].

      feature_names:
        The feature order used by the last dimension of features:
          cx: bbox center x coordinate in pixels.
          cy: bbox center y coordinate in pixels.
          x: bbox top-left x coordinate in pixels.
          y: bbox top-left y coordinate in pixels.
          w: bbox width in pixels.
          h: bbox height in pixels.
          vx: center x velocity in pixels per frame.
          vy: center y velocity in pixels per frame.
          speed: center-point speed in pixels per frame.

      sample_mode:
        "sequence" when this data point uses all frames in a sequence, or
        "window" when this data point uses a fixed-length clip.

    Dimension meanings:
      O = number of objects in this sample
      T = number of frames in this sample
      2 = RGB and thermal
      F = feature dimension

    In sequence mode, T is the full sequence length. In window mode, T is window_size.
    """

    def __init__(
        self,
        csv_path: str | Path = DEFAULT_CSV,
        sample_mode: str = "sequence",
        window_size: int = 8,
        stride: int = 1,
        min_visible_frames: int = 2,
        require_both_modalities: bool = False,
        sequence: str | None = None,
    ) -> None:
        if sample_mode not in {"sequence", "window"}:
            raise ValueError("sample_mode must be 'sequence' or 'window'.")
        if window_size <= 0:
            raise ValueError("window_size must be positive.")
        if stride <= 0:
            raise ValueError("stride must be positive.")

        self.csv_path = Path(csv_path)
        self.sample_mode = sample_mode
        self.window_size = window_size
        self.stride = stride
        self.min_visible_frames = min_visible_frames
        self.require_both_modalities = require_both_modalities

        all_sequences = read_observations(self.csv_path)
        if sequence is not None:
            all_sequences = {
                name: frames for name, frames in all_sequences.items() if name == sequence
            }

        self.sequences = all_sequences
        self.index: list[tuple[str, int | None]] = []
        self._build_index()

    def _build_index(self) -> None:
        for sequence, frame_map in sorted(self.sequences.items()):
            frames = sorted(frame_map)
            if not frames:
                continue

            if self.sample_mode == "sequence":
                self.index.append((sequence, None))
                continue

            if len(frames) < self.window_size:
                continue
            for start_pos in range(0, len(frames) - self.window_size + 1, self.stride):
                self.index.append((sequence, start_pos))

    def __len__(self) -> int:
        return len(self.index)

    def __getitem__(self, idx: int) -> dict[str, Any]:
        sequence, start_pos = self.index[idx]
        frame_map = self.sequences[sequence]
        sequence_frames = sorted(frame_map)
        if start_pos is None:
            sample_frames = sequence_frames
        else:
            sample_frames = sequence_frames[start_pos : start_pos + self.window_size]
        sample_len = len(sample_frames)

        track_ids = sorted(
            {
                track_id
                for frame_id in sample_frames
                for track_id in frame_map[frame_id].keys()
            },
            key=lambda value: int(value) if value.isdigit() else value,
        )

        objects: list[dict[str, Any]] = []
        feature_blocks: list[np.ndarray] = []
        mask_blocks: list[np.ndarray] = []

        for track_id in track_ids:
            features = np.zeros(
                (sample_len, len(MODALITIES), len(FEATURE_NAMES)),
                dtype=np.float32,
            )
            mask = np.zeros((sample_len, len(MODALITIES)), dtype=bool)
            category_id = -1
            category_name = ""

            for t, frame_id in enumerate(sample_frames):
                row = frame_map[frame_id].get(track_id)
                if row is None:
                    continue

                if row.get("category_id", "") != "":
                    category_id = int(float(row["category_id"]))
                if row.get("category_name", ""):
                    category_name = row["category_name"]

                for m, modality in enumerate(MODALITIES):
                    feature, visible = extract_feature(row, modality)
                    features[t, m, :] = feature
                    mask[t, m] = visible

            visible_rgb = int(mask[:, 0].sum())
            visible_thermal = int(mask[:, 1].sum())
            visible_any = int(np.logical_or(mask[:, 0], mask[:, 1]).sum())

            if visible_any < self.min_visible_frames:
                continue
            if self.require_both_modalities and (visible_rgb == 0 or visible_thermal == 0):
                continue

            objects.append(
                {
                    "track_id": track_id,
                    "category_id": category_id,
                    "category_name": category_name,
                    "visible_rgb_frames": visible_rgb,
                    "visible_thermal_frames": visible_thermal,
                }
            )
            feature_blocks.append(features)
            mask_blocks.append(mask)

        if feature_blocks:
            feature_array = np.stack(feature_blocks, axis=0)
            mask_array = np.stack(mask_blocks, axis=0)
        else:
            feature_array = np.zeros(
                (0, sample_len, len(MODALITIES), len(FEATURE_NAMES)),
                dtype=np.float32,
            )
            mask_array = np.zeros(
                (0, sample_len, len(MODALITIES)),
                dtype=bool,
            )

        # Alignment contract:
        #   track_ids[i] belongs to features[i] and mask[i].
        #   frames[t] belongs to features[:, t] and mask[:, t].
        #   modalities[m] belongs to features[:, :, m] and mask[:, :, m].
        #   feature_names[f] belongs to features[:, :, :, f].
        return {
            "sequence": sequence,
            "frames": np.asarray(sample_frames, dtype=np.int64),
            "track_ids": [obj["track_id"] for obj in objects],
            "category_ids": np.asarray(
                [obj["category_id"] for obj in objects], dtype=np.int64
            ),
            "category_names": [obj["category_name"] for obj in objects],
            "features": feature_array,
            "mask": mask_array,
            "objects": objects,
            "modalities": list(MODALITIES),
            "feature_names": list(FEATURE_NAMES),
            "sample_mode": self.sample_mode,
        }


VTTinyMOTWindowDataset = VTTinyMOTTrajectoryDataset


def sample_to_jsonable(sample: dict[str, Any]) -> dict[str, Any]:
    compact_objects = []
    features = sample["features"]
    mask = sample["mask"]

    for obj_idx, track_id in enumerate(sample["track_ids"]):
        tracks = {}
        for modality_idx, modality in enumerate(sample["modalities"]):
            points = []
            for time_idx, frame_id in enumerate(sample["frames"].tolist()):
                if not bool(mask[obj_idx, time_idx, modality_idx]):
                    continue
                values = features[obj_idx, time_idx, modality_idx]
                points.append(
                    {
                        "frame_id": int(frame_id),
                        "center_xy": [
                            float(values[0]),
                            float(values[1]),
                        ],
                        "bbox_xywh": [
                            float(values[2]),
                            float(values[3]),
                            float(values[4]),
                            float(values[5]),
                        ],
                    }
                )
            tracks[modality] = points

        compact_objects.append(
            {
                "track_id": track_id,
                "category_id": int(sample["category_ids"][obj_idx]),
                "category_name": sample["category_names"][obj_idx],
                "tracks": tracks,
            }
        )

    return {
        "sequence": sample["sequence"],
        "frames": sample["frames"].tolist(),
        "num_objects": len(sample["track_ids"]),
        "modalities": sample["modalities"],
        "feature_names": sample["feature_names"],
        "objects": compact_objects,
    }


def main() -> None:
    args = parse_args()
    dataset = VTTinyMOTTrajectoryDataset(
        csv_path=args.csv_path,
        sample_mode=args.sample_mode,
        window_size=args.window_size,
        stride=args.stride,
        min_visible_frames=args.min_visible_frames,
        require_both_modalities=args.require_both_modalities,
        sequence=args.sequence,
    )

    print(f"num_samples={len(dataset)}")
    limit = min(args.limit, len(dataset))
    for idx in range(limit):
        sample = dataset[idx]
        print(json.dumps(sample_to_jsonable(sample), ensure_ascii=False))


if __name__ == "__main__":
    main()
